update calculate date in database side
darwin-eu-dev/PatientProfiles pull request #361
Opened 2023-09-13 14:56 UTC by ilovemane

@catalamarti I am doing this step by step so you might see several pull request.

2023-09-13 23:07 UTC, ilovemane commented
@catalamarti The failing coverage was due to calculating the median of the date in the database side and 
doing something like this below in a loop.
```
.fns = getFunctions(functions[k]) 
```
Nevertheless I have made numeric and binary to run in database side.

2023-09-14 08:29 UTC, catalamarti commented
Thank you very much @ilovemane !

2023-09-15 09:17 UTC, catalamarti requested changes

2023-09-15 09:17 UTC, catalamarti commented on R/summariseResult.R
> +          dplyr::mutate(variable = stringr::str_replace(.data$variable,  "_[^_]+$", ""))
1) can you put the mutate after the collect?
2) this line (if I understand correctly) substitute anything after the first "_" by: "", so if the variable that we are summarisig is "time_to_event" this will be reduced to "time", right? Can we instead change this to:
```
id <- nchar(names(functionName)) + 1
variable = substr(.data$variable, 1, nchar(.data$variable) - id)
```
or something similar?

2023-09-15 09:18 UTC, catalamarti commented on R/summariseResult.R
> +          dplyr::mutate(variable = stringr::str_replace(.data$variable,  "_[^_]+$", ""))
can you add a test to make sure that this works too? @ilovemane

2023-09-19 12:02 UTC, catalamarti approved these changes

2023-09-19 12:03 UTC, merged