plt func
darwin-eu-dev/PatientProfiles pull request #467
Opened 2024-03-05 20:56 UTC by MimiYuchenGuo

#466

2024-03-08 11:47 UTC, catalamarti requested changes

2024-03-08 11:47 UTC, catalamarti commented on NAMESPACE
> +export(plotSummariseLargeScaleCharacteristics)
plotLargeScaleCharacteristics

2024-03-08 11:47 UTC, catalamarti commented on R/plotSummariseLargeScaleCharacteristics.R
> +plotSummariseLargeScaleCharacteristics <- function(data, cohort_name, compare_cohorts = FALSE,
variables should be camelCase

2024-03-08 11:47 UTC, catalamarti commented on R/plotSummariseLargeScaleCharacteristics.R
> +                                                   cohort_2_name = NULL,
rename to reference?

2024-03-08 11:47 UTC, catalamarti commented on R/plotSummariseLargeScaleCharacteristics.R
> +    stop("Input data is empty. Please provide a non-empty data frame.")
could we just return an empty plot?

2024-03-08 11:47 UTC, catalamarti commented on R/plotSummariseLargeScaleCharacteristics.R
> +#' @param cohort_name the cohort name you want to characterise
they can do the filtering for you right? I would delete this option

2024-03-08 11:48 UTC, catalamarti commented
Could you please add a vignette showing the plot and how to use it? @MimiYuchenGuo

2024-03-13 02:57 UTC, MimiYuchenGuo commented
Now you can do boxplot barplot and scatterplot

2024-03-13 18:32 UTC, catalamarti approved these changes

2024-03-13 18:32 UTC, merged