overlap functions
darwin-eu-dev/PatientProfiles pull request #470
Opened 2024-03-06 12:26 UTC by nmercadeb

- summarisedCohortOverlap
- tableCohortOverlap
- plotCohortOverlap

2024-03-08 20:18 UTC, catalamarti requested changes

2024-03-09 12:07 UTC, nmercadeb commented on R/plotSummarised.R
> +                              overlapLabel = "{cohort_name_reference};
The line break was not to traspass the "line" in R, not to have a line break in the axis labels of the plot

2024-03-09 12:09 UTC, nmercadeb commented on R/summariseCohortOverlap.R
> +summariseCohortOverlap <- function(cohort) {
I was also wondering if we should allow strata? @catalamarti @edward-burn

2024-03-15 11:39 UTC, catalamarti approved these changes

2024-03-15 12:44 UTC, merged